### ISSUE TITLE
Depiction description 

### ISSUE THREAD

**Issue by avitzavi** [brendonjkding/CCNoiseControl#1]
Hey, none of your package depictions contain the words “AirPods“ in them. Consider adding it so people who search for AirPod tweaks can find your awesome work!

**Comment by brendonjkding** [comment]
I will add it in the next version, though I think the name is clear enough.

**Comment by avitzavi** [comment]
Names are super clear on all your AirPods packages. 
But when I bought my AirPods last month and searched Cydia for “AirPods” to see what was available your work did not show up, which is a big miss because your tweaks are awesome.

**Comment by brendonjkding** [comment]
Added in 0.0.3
